routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});

Route::get('/user', function () {
    return view('list');
});

Route::get('/add', function () {
    return view('add');

});

Route::get('/edit', function () {
    return view('edit');

});

Route::resource('people', 'PeopleController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class PeopleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    //    DB::select('select * from people');
       $data = DB::table('people')->get();
       
    //    dd($data);
       return view('list')->with('people',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fname' => 'required|min:3|max:10',
            'lname' => 'required|min:3|max:10',
            'age' =>  'required|numeric',
        ]);
        DB::table('people')->insert([
            'fname'=>$request->fname,
            'lname'=>$request->lname,
            'age'=> $request->age,
            'created_at'=>now("Asia/Bangkok"),
            'updated_at'=>now("Asia/Bangkok")

        ]);
        return redirect('people')->with('success', 'Stock has been Add Successfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('people')->find($id);
        return view('edit')->with('people',$data);
     
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'fname' => 'required|min:3|max:10',
            'lname' => 'required|min:3|max:10',
            'age' =>  'required|numeric',
        ]);
        DB::table('people')->where('id','=',$id)
        ->update([
            'fname'=>$request->fname,
            'lname'=>$request->lname,
            'age'=> $request->age,
            'created_at'=>now("Asia/Bangkok"),
            'updated_at'=>now("Asia/Bangkok")

        ]);
        return redirect('people')->with('success', 'People has been Updated '.'ID:' .$id .' '.'Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('people')->where('id','=', $id)->delete();
        return redirect('people')->with('success', 'People has been deleted '.'ID:' .$id .' '.'Successfully');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index($id){
        $sum = $id + 2;
        // $arr = [
        //     'id'=> 1,
        //     'firstname' => 'TK',
        //     'lasname'=>'mnr',
        //     'skill'=>[
        //         'thai'=> 100,
        //         'en'=> 60
        //     ]
        //     ];
            // dd($arr);
     
        return view('user')->with('id',$id);
    }
}

resources/views/add.blade.php
@extends('layouts.master')
@section('title','add')
@section('content')
<form action="{{ url('people')}}" method="post">
    @csrf
    <div class="form-group">
        <label for="fname">firstname</label>
        <input id="fname" class="form-control" type="text" name="fname">
    </div>
    <div class="form-group">
            <label for="lname">lastname</label>
            <input id="lname" class="form-control" type="text" name="lname">
        </div>
        <div class="form-group">
                <label for="age">age</label>
                <input id="age" class="form-control" type="text" name="age">
            </div>
            <button type="submit" class="btn btn-success">Save</button>
   @if ($errors->any())
   <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
            <li> {{ $error }}</li>
                @endforeach
            </ul>
   </div>
   @endif
        </form>

@endsection

resources/views/edit.blade.php
@extends('layouts.master')
@section('title','edit')
@section('content')
<form action="{{ url('people',[$people->id])}}" method="post">
    @csrf
    @method('put')
    <h1>Edit People</h1>
             
    <div class="form-group">
           
        <input id="fname" hidden class="form-control" type="text" name="fname" value="{{ $people->id}}">
   
    <div class="form-group">
        <label for="fname">firstname</label>
    <input id="fname" class="form-control" type="text" name="fname" value="{{ $people->fname}}">
    </div>
    <div class="form-group">
            <label for="lname">lastname</label>
            <input id="lname" class="form-control" type="text" name="lname" value="{{ $people->lname}}">
        </div>
        <div class="form-group">
                <label for="age">age</label>
                <input id="age" class="form-control" type="text" name="age" value="{{ $people->age}}">
            </div>
            <button type="submit" class="btn btn-success">Edit</button>
   @if ($errors->any())
   <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
            <li> {{ $error }}</li>
                @endforeach
            </ul>
   </div>
   @endif
        </form>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
  @section('css')
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  @show


    <title>@yield('title')</title>
</head>
<body>

  {{-- @include('layouts.navbar') --}}
  
<div class="container mt-5">
   {{-- <h1 class="main-red">Heyyyyyyy</h1> --}}
    @yield('content')


    
  
</div>
</body>
</html>

resources/views/layouts/navbar.blade.php
<h1>Navbar</h1>

resources/views/list.blade.php
@extends('layouts.master')
@section('title','list')
@section('css')
   @parent
<link rel="stylesheet" href="{{ asset('css/main.css') }}">
<style>
  
</style>
@endsection
@section('content')

@if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />


  @endif
<div class="col-md-12 text-md-right">
  <a href="add" class= "btn btn-success" id ="add" >ADD</a>
</div>
  <br/>
    <table class="table text-md-center" >
        <thead class="thead-dark">
            <th>ID</th>
            <th>Fname</th>
            <th>Lname</th>
            <th>AGE</th>
            <th>Create Date</th>
            <th>Update Date</th>
            <th>Action Button</th>
            
        </thead>
        <tbody>
            @foreach ($people as $p)
            <tr>
            <td > {{ $p->id }}</td>
            <td>{{ $p->fname}}</td>
            <td>{{ $p->lname}}</td>
            <td>{{ $p->age}}</td>
            <td>{{ date('d-m-Y', strtotime($p->created_at)) }}</td>
            <td>{{ date('d-m-Y', strtotime($p->updated_at)) }}</td>
            <td> 
                <div class="form-inline" >
                {{-- <a href="{{route('people/'.$p->id.'/edit')}}" class="btn btn-primary">Edit</a> --}}
                <div  style="margin-right:20px;">
                <a href="{{ route('people.edit', $p->id) }}" class="btn btn-primary">Edit</a>
            </div>
                <form action="{{ route('people.destroy',[$p->id])}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                      </form>
                    </div>
            </td>
 </div>
            <td>
                   
                </td>
                </tr>
            @endforeach
           
        </tbody>
    </table>
@endsection